[package]
name = "datahub-formula"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
datahub-kernel.workspace = true
num-traits.workspace = true
serde.workspace = true
thiserror.workspace = true
wasmtime.workspace = true

[lints]
workspace = true
