[package]
name = "datahub-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
datahub-kernel.workspace = true
datahub-persistence-pg.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
